/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : PE_LDD.h.h
**     Project     : ProcessorExpert
**     Processor   : MCF51JF128VLH
**     Version     : Component 01.000, Driver 01.02, CPU db: 3.00.000
**     Compiler    : CodeWarrior MCF C Compiler
**     Date/Time   : 2012-02-07, 12:18, # CodeGen: 7
**     Abstract  : Default PE_LDD.h header file.
**                 MQX BSP provides its own "default" version of PE_LDD.h file
**                 (used as the main include of the PE files).
**                 Once the PE generates the file in <project>/Generated_Code folder,
**                 the PE_LDD.h file should be taken from the new location.
**                 The include search path order will be used to accomplish this behavior.
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __PE_LDD_H
    #define __PE_LDD_H

    /* Empty version of PE_LDD.h */
    #undef PE_LDD_VERSION

#endif  /* __PE_LDD_H */

